#+title: Project 1
#+subtitle: Machine Learning
#+author: Brian Brunner
# #+options: toc:nil

* Environment
I installed all of the dependencies using poetry, but I don't think I used any odd versions so that probably isn't relevant. If there are issues, the versions of libraries I used are listed in the =pyproject.toml= file at the root.

* Running tests
I converted the project description to a doctest, so just running ~src/ml.py~ should test the entire module against your sample runs, with noted modifications. In particular, I changed the type of errors to an ndarray and only ran until errors were 0, as per point 2.

It will exit success if success, else the exit code is number of failures. If you run with the ~-v~ flag, it will print a detailed report of what was run. The =# items had no tests= just means they didn't have specific tests, but everything is being tested in the module level docstring.

It also outputs the graphs in the description to the plots folder for review.

* Using
The docstring for the module shows example usage, but it is identical to the example use, so I assume you're familiar.

* Data I tested against
My tests are added to the bottom of the module docstring.

* Features
I added all the methods listed, everything should work as described in project description.
